export type WorkflowState =
  | 'step_1_icp'
  | 'step_2_competitors'
  | 'step_3_seeds'
  | 'step_4_longtails'
  | 'step_4_longtails_running'
  | 'step_4_longtails_failed'
  | 'step_5_filtering'
  | 'step_5_filtering_running'
  | 'step_5_filtering_failed'
  | 'step_6_clustering'
  | 'step_6_clustering_running'
  | 'step_6_clustering_failed'
  | 'step_7_validation'
  | 'step_7_validation_running'
  | 'step_7_validation_failed'
  | 'step_8_subtopics'
  | 'step_8_subtopics_running'
  | 'step_8_subtopics_failed'
  | 'step_9_articles'
  | 'step_9_articles_running'
  | 'step_9_articles_failed'
  | 'completed'

export type WorkflowEvent =
  | 'ICP_COMPLETED'
  | 'COMPETITORS_COMPLETED'
  | 'SEEDS_APPROVED'
  | 'LONGTAILS_COMPLETED'
  | 'FILTERING_COMPLETED'
  | 'CLUSTERING_COMPLETED'
  | 'VALIDATION_COMPLETED'
  | 'SUBTOPICS_APPROVED'
  | 'ARTICLES_COMPLETED'
  | 'HUMAN_RESET'
