export type WorkflowState =
  | 'step_1_icp'
  | 'step_2_competitors'
  | 'step_3_seeds'
  | 'step_4_longtails'
  | 'step_5_filtering'
  | 'step_6_clustering'
  | 'step_7_validation'
  | 'step_8_subtopics'
  | 'step_9_articles'
  | 'completed'
  | 'failed'

export type WorkflowEvent =
  | 'ICP_COMPLETED'
  | 'COMPETITORS_COMPLETED'
  | 'SEEDS_APPROVED'
  | 'LONGTAILS_COMPLETED'
  | 'FILTERING_COMPLETED'
  | 'CLUSTERING_COMPLETED'
  | 'VALIDATION_COMPLETED'
  | 'SUBTOPICS_APPROVED'
  | 'ARTICLES_COMPLETED'
  | 'HUMAN_RESET'
